import pytest

from systemone_gate.guard_rules import evaluate_command

# Commands deliberately different from the calibration dataset, so these cases test the rules and not the data.
MUST_BLOCK = [
    ("kubectl delete namespace prod", "k8s-delete-namespace"),
    ("kubectl delete ns/production", "k8s-delete-namespace"),
    ("kubectl -n kube-system delete namespace prd-eu", "k8s-delete-namespace"),
    ("kubectl delete namespaces --all", "k8s-delete-namespace"),
    ("kubectl delete pvc --all", "k8s-delete-all-volumes"),
    ("kubectl delete persistentvolumeclaims -A", "k8s-delete-all-volumes"),
    ("terraform destroy -auto-approve", "terraform-destroy"),
    ("tofu destroy --auto-approve", "terraform-destroy"),
    ("terraform apply -destroy -auto-approve", "terraform-destroy"),
    ("aws s3 rb s3://customer-data --force", "aws-s3-remove-bucket"),
    ("aws s3 rm s3://customer-data/ --recursive", "aws-s3-empty-bucket"),
    ("gcloud sql instances delete orders --quiet", "gcloud-delete-resource"),
    ("gcloud projects delete my-project -q", "gcloud-delete-resource"),
    ("az group delete -n rg-live --yes", "az-delete-resource"),
    ("docker system prune -a --volumes -f", "docker-prune-volumes"),
    ("docker volume prune -f", "docker-prune-volumes"),
    ("crontab -r", "crontab-remove"),
    ("userdel -r alice", "user-remove-home"),
    ("deluser --remove-home bob", "user-remove-home"),
    ("redis-cli FLUSHDB", "redis-flush"),
    ("redis-cli -h cache flushall", "redis-flush"),
    ("dropdb orders", "database-drop"),
    ("mysqladmin -f drop orders", "database-drop"),
    ("git branch -D master", "git-delete-protected-branch"),
    ("git branch --delete --force main", "git-delete-protected-branch"),
    ("git clean -xfd", "git-clean-ignored"),
    ("git clean -fX", "git-clean-ignored"),
    ("find / -name '*.log' -delete", "find-delete-root"),
    ("find /etc -type f -exec rm {} +", "find-delete-root"),
    ("shred -u ~/.ssh/id_ed25519", "shred-sensitive"),
    ("shred /dev/sda", "shred-sensitive"),
    ("truncate -s 0 /var/lib/postgresql/14/main/base/1", "truncate-database-file"),
    ("mv /srv/data /dev/null", "mv-to-devnull"),
    ("rm -rf .git", "rm-recursive-git-dir"),
    ("rm -rf /etc/ssh", "rm-recursive-service-dir"),
    ("rm -rf /var/lib/mysql", "rm-recursive-service-dir"),
    ("rm -rf /usr/*", "rm-recursive-system-dir"),
    # options that take a separate value must not hide the verb or the target
    ("kubectl delete -o name ns prod", "k8s-delete-namespace"),
    ("kubectl delete --grace-period 0 ns prod", "k8s-delete-namespace"),
    ("kubectl delete pvc,pv --all", "k8s-delete-all-volumes"),
    ("docker -H tcp://host:2375 volume prune -f", "docker-prune-volumes"),
    ("aws s3 rm --recursive --exclude '*.log' s3://customer-data", "aws-s3-empty-bucket"),
    ("aws s3 rm --endpoint-url http://x:4566 s3://customer-data --recursive", "aws-s3-empty-bucket"),
    ("aws s3 rm s3://customer-data// --recursive", "aws-s3-empty-bucket"),
    ("aws s3 rm S3://customer-data/. --recursive", "aws-s3-empty-bucket"),
    ("terragrunt destroy -auto-approve", "terraform-destroy"),
    ("terragrunt run-all destroy --terragrunt-non-interactive", "terraform-destroy"),
    # find: global options, $HOME and other destructive -exec forms
    ("find -L / -delete", "find-delete-root"),
    ("find -H /etc -type f -delete", "find-delete-root"),
    ("find ~ -name '*.bak' -delete", "find-delete-root"),
    ("find / -exec /bin/rm {} +", "find-delete-root"),
    ("find /usr -exec unlink {} ;", "find-delete-root"),
    # git: -d with --force is -D, global options with a separate value
    ("git branch -d -f main", "git-delete-protected-branch"),
    ("git branch -df main", "git-delete-protected-branch"),
    ("git --git-dir .git branch -D main", "git-delete-protected-branch"),
    ("git --git-dir=.git clean -fdx", "git-clean-ignored"),
    # rm: the whole service dir tree, not just one exact level
    ("rm -rf /var/lib", "rm-recursive-service-dir"),
    ("rm -rf /var/lib/*", "rm-recursive-service-dir"),
    ("rm -rf /var/lib/postgresql/14/main", "rm-recursive-service-dir"),
    ("rm -rf /usr/lib", "rm-recursive-service-dir"),
    ("rm -rf .git/objects", "rm-recursive-git-dir"),
    ("rm -rf .git/*", "rm-recursive-git-dir"),
    ("rm -rf ../.git", "rm-recursive-git-dir"),
    # path normalisation and wider sensitive targets
    ("truncate -s 0 //var/lib/mysql/x", "truncate-database-file"),
    ("truncate -s 0 /var/lib/./mysql/ibdata1", "truncate-database-file"),
    ("truncate -s 0 /var/lib/etcd/member/snap/db", "truncate-database-file"),
    ("shred -u /dev/mapper/vg-root", "shred-sensitive"),
    ("shred /dev/xvda", "shred-sensitive"),
    ("shred -u ~/.aws/credentials", "shred-sensitive"),
    ("shred -u .ssh/id_rsa", "shred-sensitive"),
    ("mv -t /dev/null x", "mv-to-devnull"),
    ("mv x //dev/null", "mv-to-devnull"),
    ("mv x /dev/./null", "mv-to-devnull"),
    ("mv x /dev/null/", "mv-to-devnull"),
    # wrappers and nesting are analysed like the plain command
    ("sudo kubectl delete namespace production", "k8s-delete-namespace"),
    ("bash -c 'redis-cli FLUSHALL'", "redis-flush"),
    ("echo ok && crontab -r", "crontab-remove"),
]

MUST_ALLOW = [
    # image/build cleanups and scoped variants reported as false positives
    "rm -rf /tmp/clone/.git",
    "rm -rf ./repo/.git/",
    "rm -rf node_modules/.git",
    "rm -rf vendor/pkg/.git",
    "rm -rf /usr/src/*",
    "rm -rf /usr/local/*",
    "rm -rf /usr/share/doc",
    "rm -rf /var/lib/cloud/*",
    "rm -rf /var/lib/apt/*",
    "truncate -s 0 /var/lib/docker/containers/abc/abc-json.log",
    "truncate -s 0 /var/lib/mysql/slow.log",
    "kubectl delete pvc -l app=tmp -A",
    "kubectl delete pvc data-0 -n x -A",
    "aws s3 rm s3://customer-data/ --recursive --dryrun",
    "aws s3 rb s3://customer-data --force --dryrun",
    "kubectl delete ns --all --dry-run=client",
    "dropdb --help",
    "redis-cli GET FLUSHALL",
    "redis-cli SET flushdb 1",
    "redis-cli -a flushall PING",
    "docker -l debug volume prune",
    "git branch -d main",
    "git --git-dir .git branch -d feature/x",
    "kubectl delete pod web-1",
    "kubectl delete namespace preview-123",
    "kubectl delete pvc data-0",
    "kubectl get namespaces",
    "terraform plan",
    "terraform destroy",
    "terraform apply -auto-approve",
    "aws s3 rm s3://customer-data/tmp/ --recursive",
    "aws s3 rm s3://customer-data/file.txt",
    "aws s3 rb s3://empty-bucket",
    "gcloud sql instances list",
    "gcloud sql instances delete orders",
    "az group list",
    "az group delete -n rg-live",
    "docker volume prune",
    "docker volume ls",
    "docker image prune -af",
    "docker system prune -f",
    "crontab -l",
    "crontab -i -r",
    "userdel alice",
    "redis-cli GET key",
    "redis-cli -n 3 DBSIZE",
    "dropdb -i orders",
    "mysqladmin status",
    "git branch -D feature/x",
    "git branch -d master",
    "git branch -a",
    "git clean -fd",
    "git clean -nfx",
    "git clean -n",
    "find . -name '*.pyc' -delete",
    "find /var/log/app -name '*.log' -delete",
    "find / -name '*.conf'",
    "shred -u notes.txt",
    "truncate -s 0 app.log",
    "truncate -s 0 /var/lib/myapp/state.json",
    "mv a.txt b.txt",
    "mv old /tmp/old",
    "rm -rf .gitignore",
    "rm -rf .github",
    "rm -rf ./node_modules",
    "rm -rf /var/lib/apt/lists/*",
    "rm -rf /etc/nginx/conf.d/old.conf",
    "rm -rf /usr/local/share/myapp",
    "rm -f /etc/hosts.bak",
    'echo "kubectl delete namespace production"',
    "grep -r 'terraform destroy -auto-approve' docs/",
]


@pytest.mark.parametrize(("command", "rule_id"), MUST_BLOCK)
def test_blocks_destructive_infra_command(command, rule_id):
    match = evaluate_command(command)
    assert match is not None, command
    assert match.rule_id == rule_id


@pytest.mark.parametrize("command", MUST_ALLOW)
def test_allows_scoped_or_prompted_variant(command):
    assert evaluate_command(command) is None, command
